//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Sale
    {
        public int SaleId { get; set; }

        [DisplayName("Product")]
        public Nullable<int> ProductId { get; set; }
        
        [NotMapped]
        public string ProductName { get; set; }

        [DisplayName("Employee")]
        public Nullable<int> EmployeeId { get; set; }
        
        [NotMapped]
        public string EmployeeName { get; set; }

        [DisplayName("Customer")]
        public string CustomerFirstName { get; set; }
        
        [DisplayName("")]
        public string CustomerLastName { get; set; }
        public string Comment { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }

        [NotMapped]
        public List<Product> ProductCollection { get; set; }

        [NotMapped]
        public List<Employee> EmployeeCollection { get; set; }
    }
}
